apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test123-component
  description: this is test
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: inlinehockey/mytest
spec:
  lifecycle: production
  owner: my-team
  type: service
